In [2]:
import torch
from torch import nn

# Import pprint, module we use for making our print statements prettier.
import pprint

pp = pprint.PrettyPrinter()

## Tensors
Tensors are the most basic building blocks in `PyTorch`. Tensors are similar to matrices, but they have extra properties and they can represent higher dimensions. For example, a square image with 256 pixels in both sides can be represented by a `3*256*256` tensor, where the first 3 dimensions represent the color channels, red, green and blue.

### Tensor Initialization
There are several ways to instantiate tensors in `PyTorch`.

#### From a Python List
We can initialize a tensor from a `Python` list, which could include sublists. The dimensions and the data types will be automatically inferred by `PyTorch` when we use `torch.tensor()`.

In [3]:
# Initialize a tensor from a Python List
data = [
    [0, 1],
    [2, 3],
    [4, 5]
]
x_python = torch.tensor(data)

# Print the tensor
x_python

tensor([[0, 1],
        [2, 3],
        [4, 5]])

We can also call `torch.tensor()` with the optional `dtype` parameter,
which will set the data type. Some useful datatypes to be familiar with
are: `torch.bool`, `torch.float`, and `torch.long`.

In [4]:
# We are using the dtype to create a tensor of particular type
x_float = torch.tensor(data, dtype=torch.float)
x_float

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [5]:
# We are using the dtype to create a tensor of a particular type
x_bool = torch.tensor(data, dtype=torch.bool)
x_bool

tensor([[False,  True],
        [ True,  True],
        [ True,  True]])

We can also get the same tensor in our specified data type using methods
such as `float()`, `long()` etc.

In [ ]:
x_float.float()

We can also use `tensor.FloatTensor`, `tensor.LongTensor`,
 `tensor.Tensor` classes to instantiate a tensor of particular type.
 `LongTensor`s are particularly important in NLP as many methods that
 deal with indices require the indices to be passed as a `LongTensor`,
 which is a 64 bit integer.

In [7]:
# `torch.Tensor` defaults to float
# Same as torch.FloatTensor(data)
x = torch.Tensor(data)
x

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

#### From a NumPy Array
We can also initialize a tensor from a `NumPy` array.

In [8]:
import numpy as np

# Initialize a tensor from a NumPy array
ndarray = np.array(data)
x_numpy = torch.from_numpy(ndarray)

# Print the tensor
x_numpy

tensor([[0, 1],
        [2, 3],
        [4, 5]])

#### From a Tensor
We can also initialize a tensor form another tensor, using the following
methods:

* `torch.ones_like(old_tensor)`: Initializes a tensor of `1s`.
* `torch.zeros_like(old_tensor)`: Initializes a tensor of `0s`.
* `torch.rand_like(old_tensor)`: Initializes a tensor where all the
elements are sampled from a **uniform distribution** between `0` and `1`.
* `torch.randn_like(old_tensor)`: Initializes a tensor where all the
elements are sampled from a **normal distribution**.

All of these methods preserve the tensor properties of the original
tensor passed in, such as the `shape` and `device`.

In [11]:
# Initialize a base tensor
x = torch.tensor([[1., 2], [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [12]:
# Initialize a tensor of 0s
x_zeros = torch.zeros_like(x)
x_zeros

tensor([[0., 0.],
        [0., 0.]])

In [13]:
# Initialize a tensor of 1s
x_ones = torch.ones_like(x)
x_ones

tensor([[1., 1.],
        [1., 1.]])

In [15]:
# Initialize a tensor where each element is sampled from a uniform distribution
# between 0 and 1
x_rand = torch.rand_like(x)
x_rand

tensor([[0.1863, 0.8709],
        [0.9112, 0.6468]])

In [16]:
# Initialize a tensor where each element is sampled form a normal distribution
x_randn = torch.randn_like(x)
x_randn

tensor([[-0.1762,  0.0459],
        [ 0.4136, -0.4407]])